{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
  labels: {{- include "actual-budget.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeName: {{ .Values.persistence.user.volumeName }}
{{- end }}
