{{- if and .Values.persistence.enabled .Values.persistence.storageClassName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  labels: {{- include "code-server.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeName: {{ .Values.persistence.volumeName }}
{{- end }}
