apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server.name" . }}
  labels: {{ include "code-server.labels" . | nindent 4 }}
data: {{- toYaml .Values.secret.data | nindent 4 }}
type: Opaque
