apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nzbget.serviceName }}
  labels:
    {{- include "onn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.nzbget.port }}
      targetPort: {{ .Values.service.nzbget.portName }}
      protocol: TCP
      name: {{ .Values.service.nzbget.portName }}
  selector:
    {{- include "onn.selectorLabels" . | nindent 4 }}
