apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sonarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sonarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: 8989 
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ .Values.configMap.name }}
          volumeMounts:
          {{- if .Values.persistence.nfs_enabled }}
          - name: {{ .Values.persistence.config.name }}
            mountPath: /config
          - name: {{ .Values.persistence.tv_nfs.name }}
            mountPath: /tv
          - name: {{ .Values.persistence.downloads_nfs.name }}
            mountPath: /downloads
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ .Values.persistence.config.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.claimName }}
      {{- if .Values.persistence.nfs_enabled }}
      - name: {{ .Values.persistence.tv_nfs.name }}
        nfs: {{- toYaml .Values.persistence.tv_nfs.nfs | nindent 10 }}
      - name: {{ .Values.persistence.downloads_nfs.name }}
        nfs: {{- toYaml .Values.persistence.downloads_nfs.nfs | nindent 10 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
